import { Patient, ScreeningCase, RetinalFinding } from './types';

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'PT-8842',
    name: 'Lakshmi Bai',
    age: 58,
    sex: 'Female',
    diabetesHistory: 'Type 2 DM (11 years) • HbA1c 8.4%',
    cameraDevice: 'Remidio NM-FOP',
    lastScreeningDate: '2025-03-12',
    phcLocation: 'Telangana East PHC #04',
  },
  {
    id: 'PT-8843',
    name: 'Ramesh Verma',
    age: 64,
    sex: 'Male',
    diabetesHistory: 'Type 2 DM (16 years) • HbA1c 9.1%',
    cameraDevice: 'Forus 3nethra classic',
    lastScreeningDate: '2024-11-05',
    phcLocation: 'Telangana East PHC #04',
  },
  {
    id: 'PT-8844',
    name: 'Anitha Reddy',
    age: 49,
    sex: 'Female',
    diabetesHistory: 'Type 2 DM (5 years) • HbA1c 7.2%',
    cameraDevice: 'Zeiss Visucam 500',
    lastScreeningDate: 'First Screening',
    phcLocation: 'Telangana East PHC #04',
  },
  {
    id: 'PT-8845',
    name: 'Kishore Kumar',
    age: 52,
    sex: 'Male',
    diabetesHistory: 'Type 2 DM (8 years) • HbA1c 7.8%',
    cameraDevice: 'Topcon TRC-NW400',
    lastScreeningDate: '2025-01-20',
    phcLocation: 'Telangana East PHC #04',
  },
];

// Calibrated coordinates matching exact pixel lesion locations in /samples/moderate_dr.jpg
export const MOCK_FINDINGS_CASE_1: RetinalFinding[] = [
  {
    id: 'FND-01',
    name: 'Microaneurysms',
    count: 14,
    severity: 'mild',
    category: 'structural',
    locationDescription: 'Temporal region, 2-3 disc diameters from macula',
    coords: [
      { x: 24, y: 38, radius: 4 },
      { x: 22, y: 46, radius: 3 },
      { x: 25, y: 54, radius: 4 },
      { x: 31, y: 42, radius: 3 },
      { x: 33, y: 58, radius: 4 },
      { x: 20, y: 62, radius: 3 },
      { x: 27, y: 32, radius: 3 },
    ],
  },
  {
    id: 'FND-02',
    name: 'Hemorrhages',
    count: 5,
    severity: 'moderate',
    category: 'structural',
    locationDescription: 'Inferotemporal quadrant near major vascular branch',
    coords: [
      { x: 56, y: 8, radius: 10 },    // Superior blot hemorrhage
      { x: 63, y: 84, radius: 10 },   // Inferior blot hemorrhage
      { x: 15, y: 55, radius: 9 },    // Temporal blot hemorrhage
      { x: 21, y: 68, radius: 8 },    // Inferotemporal blot hemorrhage
      { x: 88, y: 58, radius: 8 },    // Nasal blot hemorrhage near disc
    ],
  },
  {
    id: 'FND-03',
    name: 'Hard Exudates',
    count: 8,
    severity: 'moderate',
    category: 'colour',
    locationDescription: 'Perimacular circinate ring formation (L*a*b* B-channel view)',
    coords: [
      { x: 38, y: 32, radius: 7 },   // Upper arc exudate 1
      { x: 48, y: 31, radius: 6 },   // Upper arc exudate 2
      { x: 56, y: 34, radius: 7 },   // Upper arc exudate 3
      { x: 34, y: 64, radius: 8 },   // Lower arc exudate 1
      { x: 44, y: 66, radius: 7 },   // Lower arc exudate 2
      { x: 54, y: 63, radius: 6 },   // Lower arc exudate 3
      { x: 28, y: 46, radius: 7 },   // Temporal circinate ring tip
    ],
  },
  {
    id: 'FND-04',
    name: 'Vascular Abnormalities',
    count: 2,
    severity: 'mild',
    category: 'structural',
    locationDescription: 'Venous beading visible in superior arc',
    coords: [
      { x: 68, y: 28, radius: 9 },   // Superior arcade vessel curve
      { x: 72, y: 68, radius: 9 },   // Inferior arcade vessel curve
    ],
  },
];

export const MOCK_CASES: ScreeningCase[] = [
  {
    id: 'CASE-2026-001',
    patient: MOCK_PATIENTS[0],
    timestamp: '2026-09-06T10:14:00Z',
    imageUrl: '/samples/moderate_dr.jpg',
    quality: {
      fovDetected: true,
      focusAcceptable: true,
      exposureAcceptable: true,
      retinaVisible: true,
      blurScore: 0.94,
      illuminationUniformity: 0.91,
    },
    qualityStatus: 'passed',
    status: 'completed',
    result: {
      diagnosis: 'Moderate Non-Proliferative Diabetic Retinopathy (NPDR)',
      icdrLevel: 2,
      severity: 'moderate',
      confidence: 'High',
      confidenceScore: 96.4,
      triageTier: 'Tier 2 (Priority Review)',
      findings: MOCK_FINDINGS_CASE_1,
      progressionRisk: 42,
      recallAdvice: '6 Months',
      csmeThreatDetected: true,
      csmeFoveaDistanceDiscDiameters: 0.45,
      clinicalGuidance: {
        icd10Code: 'E11.329',
        referralTimeline: 'Refer to District Hospital within 3 to 6 months',
        guidelineSource: 'AAO Preferred Practice Pattern (PPP 2023) & AIIMS Guidelines',
        doctorTechnicalNote: 'DIAGNOSIS: Moderate NPDR (ETDRS Stage 2)\nICD-10: E11.329\nTRIAGE: Routine Specialist Referral\nPROTOCOL: AAO Table 4.3 indicated referral for dilated biomicroscopy and baseline macular OCT.\nFINDINGS: Multiple microaneurysms, dot-and-blot hemorrhages across 2 quadrants, temporal lipid exudates.\nMACULAR STATUS: Hard exudates detected within 0.45 DD of foveal center (CSME risk). Strict glycemic control (HbA1c < 7.0%) advised.',
        patientSummaryEn: 'Moderate diabetic eye changes: Small bleeding spots and protein deposits are present in your retina. An eye specialist review is recommended within 3 to 6 months. Maintain strict blood sugar and blood pressure control.',
        patientSummaryHi: 'मध्यम स्थिति: आँख के पर्दे में खून के छोटे धब्बे और रिसाव के निशान देखे गए हैं। अगले 3 से 6 महीने के भीतर नेत्र विशेषज्ञ से अपनी आँखों की पूरी जांच करवाएं और शुगर को पूरी तरह नियंत्रित रखें।',
        safetyAuditPassed: true,
      },
    },
    doctorReviewStatus: 'pending',
    waitingTimeMinutes: 18,
    priority: 'HIGH PRIORITY',
    synced: true,
  },
  {
    id: 'CASE-2026-002',
    patient: MOCK_PATIENTS[1],
    timestamp: '2026-09-06T11:30:00Z',
    imageUrl: '/samples/moderate_dr.jpg',
    quality: {
      fovDetected: true,
      focusAcceptable: true,
      exposureAcceptable: true,
      retinaVisible: true,
      blurScore: 0.88,
      illuminationUniformity: 0.86,
    },
    qualityStatus: 'passed',
    status: 'completed',
    result: {
      diagnosis: 'Severe Non-Proliferative Diabetic Retinopathy (NPDR)',
      icdrLevel: 3,
      severity: 'severe',
      confidence: 'High',
      confidenceScore: 98.1,
      triageTier: 'Tier 3 (Specialist Escalation)',
      findings: [
        ...MOCK_FINDINGS_CASE_1,
        {
          id: 'FND-05',
          name: 'Hemorrhages',
          count: 18,
          severity: 'severe',
          category: 'structural',
          locationDescription: 'Widespread blot hemorrhages in 4 quadrants',
          coords: [
            { x: 56, y: 8, radius: 10 },
            { x: 88, y: 58, radius: 10 },
          ],
        },
      ],
      progressionRisk: 78,
      recallAdvice: '3 Months (Urgent)',
      csmeThreatDetected: true,
      csmeFoveaDistanceDiscDiameters: 0.28,
      clinicalGuidance: {
        icd10Code: 'E11.349',
        referralTimeline: 'Urgent specialist referral within 2 to 4 weeks',
        guidelineSource: 'AAO Preferred Practice Pattern (PPP 2023) Section 4.4 & AIIMS',
        doctorTechnicalNote: 'DIAGNOSIS: Severe NPDR (ETDRS Stage 3)\nICD-10: E11.349\nTRIAGE: Urgent Tele-Ophthalmology Escalation\nPROTOCOL: AAO PPP Section 4.4 mandates vitreoretinal specialist referral within 2 to 4 weeks (50% 1-year progression risk to high-risk PDR).\nFINDINGS: Intraretinal hemorrhages >=20 in all 4 quadrants (ETDRS Rule 4 met), venous beading in 2 quadrants.\nMACULAR STATUS: CSME suspected within 0.28 DD of foveal center. Urgent FFA and macular OCT indicated.',
        patientSummaryEn: 'Urgent medical attention needed: Serious diabetic damage and poor blood circulation are present across your retina. You are at high risk of rapid vision loss. Visit an eye hospital within 2 to 4 weeks for specialized retinal scans and possible laser/injection therapy.',
        patientSummaryHi: 'तत्काल ध्यान देने की आवश्यकता: आपकी आँख के पर्दे में गंभीर खराबी और खून के बहाव में रुकावट देखी गई है। अगले 2 से 4 सप्ताह के भीतर किसी बड़े अस्पताल में रेटिना विशेषज्ञ को दिखाएं ताकि समय रहते लेजर या इंजेक्शन से रोशनी बचाई जा सके।',
        safetyAuditPassed: true,
      },
    },
    doctorReviewStatus: 'pending',
    waitingTimeMinutes: 45,
    priority: 'HIGH PRIORITY',
    synced: false,
  },
  {
    id: 'CASE-2026-003',
    patient: MOCK_PATIENTS[2],
    timestamp: '2026-09-06T09:05:00Z',
    imageUrl: '/samples/normal_fundus.jpg',
    quality: {
      fovDetected: true,
      focusAcceptable: true,
      exposureAcceptable: true,
      retinaVisible: true,
      blurScore: 0.97,
      illuminationUniformity: 0.95,
    },
    qualityStatus: 'passed',
    status: 'completed',
    result: {
      diagnosis: 'No Apparent Diabetic Retinopathy (Normal)',
      icdrLevel: 0,
      severity: 'normal',
      confidence: 'High',
      confidenceScore: 99.2,
      triageTier: 'Tier 1 (Auto-Cleared)',
      findings: [],
      progressionRisk: 4,
      recallAdvice: '12 Months',
      csmeThreatDetected: false,
      clinicalGuidance: {
        icd10Code: 'E11.9 / Z13.5',
        referralTimeline: 'Annual follow-up in 12 months at Primary Health Centre (PHC)',
        guidelineSource: 'AAO Preferred Practice Pattern (PPP 2023) Table 4.1',
        doctorTechnicalNote: 'DIAGNOSIS: No Apparent Diabetic Retinopathy (ETDRS Stage 0)\nICD-10: E11.9 / Z13.5\nTRIAGE: Routine Annual Community Screening\nPROTOCOL: AAO Table 4.1 confirms annual dilated fundus evaluation. Emphasize systemic glycemic target (HbA1c < 7.0%) and BP control (< 130/80 mmHg).\nFINDINGS: Clean retinal vascular tree, absence of microaneurysms, hemorrhages, or lipid exudates.\nMACULAR STATUS: Normal foveal avascular zone; macula clear.',
        patientSummaryEn: 'Good news: Your retina examination shows no signs of diabetic damage at this time. Your blood vessels appear clear and healthy. Return for your next routine eye check in 12 months and maintain strict blood sugar control.',
        patientSummaryHi: 'अच्छी खबर: आपकी आँख के पर्दे (रेटिना) में मधुमेह का कोई नुकसान नहीं पाया गया है। खून की नसें स्वस्थ हैं। 12 महीने बाद अपनी अगली नियमित आँख की जांच करवाएं और शुगर को नियंत्रित रखें।',
        safetyAuditPassed: true,
      },
    },
    doctorReviewStatus: 'approved',
    waitingTimeMinutes: 5,
    priority: 'STANDARD REVIEW',
    synced: true,
  },
  {
    id: 'CASE-2026-004',
    patient: MOCK_PATIENTS[3],
    timestamp: '2026-09-06T12:10:00Z',
    imageUrl: '/samples/normal_fundus.jpg',
    quality: {
      fovDetected: true,
      focusAcceptable: true,
      exposureAcceptable: true,
      retinaVisible: true,
      blurScore: 0.91,
      illuminationUniformity: 0.89,
    },
    qualityStatus: 'passed',
    status: 'completed',
    result: {
      diagnosis: 'Mild Non-Proliferative Diabetic Retinopathy (NPDR)',
      icdrLevel: 1,
      severity: 'mild',
      confidence: 'High',
      confidenceScore: 94.8,
      triageTier: 'Tier 1 (Auto-Cleared)',
      findings: [
        {
          id: 'FND-06',
          name: 'Microaneurysms',
          count: 3,
          severity: 'mild',
          category: 'structural',
          locationDescription: 'Isolated MAs in superotemporal quadrant',
          coords: [{ x: 24, y: 38, radius: 4 }],
        },
      ],
      progressionRisk: 14,
      recallAdvice: '12 Months',
      csmeThreatDetected: false,
      clinicalGuidance: {
        icd10Code: 'E11.319',
        referralTimeline: 'Follow-up in 6 to 12 months at PHC or Community Health Centre',
        guidelineSource: 'AAO Preferred Practice Pattern (PPP 2023) Table 4.2',
        doctorTechnicalNote: 'DIAGNOSIS: Mild NPDR (ETDRS Stage 1)\nICD-10: E11.319\nTRIAGE: Monitored Primary Eye Care\nPROTOCOL: AAO Table 4.2 indicates low 1-year progression risk (~5%). Systemic medical optimization: rigorous glycemic control (HbA1c < 7.0%) and lipid panel management. Routine review in 6–12 months.\nFINDINGS: Isolated microaneurysms detected on sub-pixel patch inspection without hard exudates or venous caliber changes.\nMACULAR STATUS: Foveal center intact; no macular edema.',
        patientSummaryEn: 'Mild changes detected: You have early, tiny pinpoint swelling in the small blood vessels of your eye. Your sight is not currently at risk. With strict sugar and diet control, progression can be stopped. Schedule a follow-up eye scan in 6 to 12 months.',
        patientSummaryHi: 'शुरुआती बदलाव: आपकी आँख की बारीक नसों में बहुत छोटे उभार (माइक्रोएन्यूरिज्म) देखे गए हैं। अभी आपकी दृष्टि को कोई खतरा नहीं है। सख्त शुगर नियंत्रण और स्वस्थ आहार से इसे रोका जा सकता है। 6 से 12 महीने बाद दोबारा अपनी आँख की जांच करवाएं।',
        safetyAuditPassed: true,
      },
    },
    doctorReviewStatus: 'pending',
    waitingTimeMinutes: 12,
    priority: 'STANDARD REVIEW',
    synced: true,
  },
];
